version: '3.3'

services:
  employees:
    image: mysql
    container_name: mysqlwdump
    ports: 
      - 3306:3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employees
      MYSQL_USER: notroot
      MYSQL_PASSWORD: pass
