version: '3.3'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysqlu
      MYSQL_PASSWORD: qwerty
