version: '3.3'

services:
  mysql:
    image: mysql-w-dump
    container_name: mysqlwdump
    ports: 
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
